### ISSUE TITLE
How do you "undo" the effects of `gdm restore`

### ISSUE THREAD

**Issue by amoghe** [sparrc/gdm#27]
I tried building a project that uses `gdm` (influxdata/telegraf @ v 1.7) and the `make` command ends up calling `gdm restore` , which then proceeds to check out all the various dependency dirs to a particular commit (detached HEAD). 

Now I want to switch all of them back to a pristine state once I'm done working on this repo , but due to dependency sprawl, a *lot* of the projects under `$GOPATH/src` is now in a detached HEAD state. 

How can I restore each of them to a state as though I had just invoked `go get` on them (i.e. all HEAD are at tip of `master`) ?

**Comment by sparrc** [comment]
This project was initially conceived as being run on a single project within it's own GOPATH, so there is no way to do that, sorry. Best advice I can give you is to checkout and build telegraf within it's own GOPATH, so that `gdm restore` does not affect your other projects.
