### ISSUE TITLE
gdm doesn't support multiple entries in $GOPATH

### ISSUE THREAD

**Issue by pavel-kolesnikov** [sparrc/gdm#9]
By design of the $GOPATH environment variable could contain multiple path delimited by colon (:) like the $PATH does.

If $GOPATH containes more than one entry, gdm will fail with error:

```
gdm restore
gdm can only be executed within a directory in the GOPATH
```

**Comment by sparrc** [comment]
thanks for the heads-up, looks like I had a string match reversed.
